doc-warnings: true
test-warnings: false
strictness: veryhigh
ignore-patterns:
    - .*init__\.py$
    - .*common.py$
ignore-paths:
    - docs
    - support 
python-targets:
    - 3

pylint:
  disable:
    anomalous-backslash-in-string

pep8:
  disable:
    - W291
    - W293
